### ISSUE TITLE
Some CSPROJ files are detected as binary when using git diff

### ISSUE THREAD

**Issue by MarkMichaelis** [IntelliTect/EssentialCSharp#9]
It appears that some CSPROJ files are getting detected as binary files so they fail to work with git diff.  All files should be changed to text files - preferably without adding a CSPROJ extension attribute.

**Comment by kodybrown** [comment]
I can add a .gitattributes file that will take care of that and any other potential issues?

**Comment by MarkMichaelis** [comment]
I was trying to avoid that because the files should just be text.  I was hoping it was caused by some errant encoding and we just had to re-write the file.  Perhaps both?  Your input is welcome.

**Comment by Keboo** [comment]
I think both probably needs to be done.

Listing file that are "binary" ([source](https://stackoverflow.com/a/35615914)) shows pretty much all of the csproj files.

Looking at the contents most (not all) csproj files have an xml declaration with an encoding of utf-16 specified. Digging a bit further, most (all?) of the csproj files appear to have a utf-16 LE BOM (0xFF 0xFE).
This is likely the cause of your `git diff` troubles.

Though you can [configure your local diff to convert the files](https://stackoverflow.com/documentation/git/273/git-diff/7327/diff-utf-16-encoded-text-and-binary-plist-files#t=201707141945227129789) I think it would be better to simply fix these files.

VS2017 for the new core csproj format (is there a fancy name for it?) generate the csproj without the XML declaration and with a UTF-8 BOM. Framework based csproj still generate the xml declaration with an encoding of utf-8 and a UTF-8 BOM.

It is probably best to:
1. Fix all of the csproj files to be UTF-8. This will likely solve your diff issues.
2. Also setup the .gitattributes to mark all .cs and .csproj files as text. Though not current necessary it is possible that at some point you will need to include fancy characters in a file. In these cases git might falsely detect file as binary rather than text.  Most (all?) git tools respect the fact that the .gitattributes files has final say over whether a file is considered text or binary.

**Comment by nlundby** [comment]
I submitted a pull request with all of the csproj files changed to UTF-8.  This did indeed solve the diff issues.

I didn't touch the .gitattributes file.  If it becomes necessary I figure it would be a quick fix.

**Comment by MarkMichaelis** [comment]
Request pulled... thanks, Neal!!! 

(Curious, how did you change all the files?)

**Comment by MarkMichaelis** [comment]
By the way Neal, what specifically did you do change a file to UTF-8?  Just curious.

**Comment by nlundby** [comment]
There used to be an advanced option in VS that allowed you to change the encoding, but this was removed in VS17 due to uncommon use.  The only method available now is to SAVE AS and select UTF-8 encoding and then overwrite the project.  The UTF-8 BOM then will cause VS to maintain UTF-8 for future changes. 

Removal of the UTF-16 declarations and overwriting the old projects was relatively smooth, but in 2 cases VS was not recognizing the new UTF-8 XML file, but a simple copy & paste operation nudged the IDE to recognize it.
